### ISSUE TITLE
Can't deploy to production

### ISSUE THREAD

**Issue by martingaleh** [apex-enterprise-patterns/fflib-apex-mocks#134] opened 2022-11-27 20:34 UTC
**Describe the bug**
When I press the button to deploy to production, there is a blue bar on top that says:
Unhandled Exception : java.lang.RuntimeException: /app/.local/share/sfdx/client/7.178.0-ce727f2/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /app/.local/share/sfdx/client/7.178.0-ce727f2/bin/node)

**To Reproduce**

Press the button
Make sure production/developer radio button selected
Click Login to Salesforce
Login to production instance

**Expected behavior**
I expect the library to be automatically deployed

**Screenshots and text of error observed**
![image](https://user-images.githubusercontent.com/283459/204158277-959e4aec-bcb2-4fe5-bf44-132b87023714.png)
**Version**
I assume the one on the initial github page is the latest version

**Comment by martingaleh** [comment] 2022-11-27 20:41
I googled further and found this:
https://githublab.com/repository/issues/afawcett/githubsfdeploy/53

And this is happening to other libraries

**Comment by ImJohnMDaniel** [comment] 2022-11-27 20:46
Closing as this is a duplicate of #133  and not an issue with this repo.  As you discovered, this is an issue with the GitHubSFDeploy tool.  See actual issue [here](https://github.com/afawcett/githubsfdeploy/issues/53).  I would suggest using the Salesforce CLI to deploy the ApexMocks codebase in the meantime.

**Closed by ImJohnMDaniel** 2022-11-27 20:46 UTC
