### ISSUE TITLE
Unable to deploy to developer org with Unhandled Exception

### ISSUE THREAD

**Issue by taoduh** [apex-enterprise-patterns/fflib-apex-mocks#135] opened 2022-11-28 20:16 UTC
**Describe the bug**

Unable to deploy to developer org

**To Reproduce**

1. Click the deploy button
2. Click the login
3. Error prints at top of screen

**Expected behavior**

mocks library installs to developer org

**Screenshots and text of error observed**
screenshot attached

Text of error which appears as a banner across top of screen

Unhandled Exception : java.lang.RuntimeException: /app/.local/share/sfdx/client/7.178.0-ce727f2/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /app/.local/share/sfdx/client/7.178.0-ce727f2/bin/node)

**Version**

yes, latest version
![Screen Shot 2022-11-28 at 12 15 27 PM](https://user-images.githubusercontent.com/158271/204372358-ffebbf22-8b61-4417-a5f4-5c413cfba3b1.png)

**Comment by ImJohnMDaniel** [comment] 2022-11-28 20:18
Closing as this is a duplicate of #133  and not an issue with this repo.  As you discovered, this is an issue with the GitHubSFDeploy tool.  See actual issue [here](https://github.com/afawcett/githubsfdeploy/issues/53).  I would suggest using the Salesforce CLI to deploy the ApexMocks codebase in the meantime.

**Closed by ImJohnMDaniel** 2022-11-28 20:18 UTC
