### ISSUE TITLE
Deploy to Salesforce Button Does not Work

### ISSUE THREAD

**Issue by Ehsanyzd** [apex-enterprise-patterns/fflib-apex-mocks#84] opened 2020-02-10 05:23 UTC
When deploying with "Deploy to Salesforce" button, this error occurs:

Deployment Started
Status: Queued 
Status: InProgress 
Status: Completed 
Deployment Complete
Failures:
customMetadata/README.md(1,1):Error parsing file: Content is not allowed in prolog.

**Comment by ImJohnMDaniel** [comment] 2020-02-10 13:53
duplicate of this issue posted to Twitter https://twitter.com/sauloefo/status/1226502794179465216

**Comment by kvarga** [comment] 2020-02-22 16:51
FYI This is breaking ability to quickly do at least 1 Trailhead module
https://trailhead.salesforce.com/content/learn/modules/apex_patterns_sl/apex_patterns_sl_apply_uow_principles

**Comment by ImJohnMDaniel** [comment] 2020-03-02 03:26
@kvarga, @Ehsanyzd, @akshaysharma3, @Maximetinu -- The issue with the GithubDeploy tool has been corrected that was causing the error mentioned in this issue.  

I would ask that you try these deployments again and let us know if you are still having issues.

**Comment by afawcett** [comment] 2020-04-07 00:40
The deploy tool has been fixed. 👍

**Closed** 2020-04-07 00:40 UTC
Labels: bug, priority

**Comment by chashmeetsingh** [comment] 2020-04-08 21:01
I can still reproduce this issue when trying to do https://trailhead.salesforce.com/content/learn/modules/apex_patterns_sl/apex_patterns_sl_apply_uow_principles on a new playground.

**Comment by ImJohnMDaniel** [comment] 2020-04-08 21:51
@afawcett Can you investigate this from your side please?

**Comment by chashmeetsingh** [comment] 2020-04-08 23:21
Not sure what changed but it seems to be working now. Thank you.
